language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
env: DB=mysql
 - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS boilerplate;" -uroot; fi

script: phpunit --configuration phpunit.xml --coverage-text
